{% set name = "google-resumable-media" %}
{% set version = "2.7.2" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5280aed4629f2b60b847b0d42f9857fd4935c11af266744df33d8074cae92fe0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - google-crc32c >=1.0,<2.0dev
  run_constrained:
    # extras
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev
    # omit google-auth because it causes downstream conflicts
    # - google-auth >=1.22.0,<2.0dev

test:
  requires:
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - johanneskoester
    - parthea
    - tswast
