{% set name = "google-resumable-media" %}
{% set version = "2.7.1" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-resumable-media-{{ version }}.tar.gz
  sha256: eae451a7b2e2cdbaaa0fd2eb00cc8a1ee5e95e16b55597359cbc3d27d7d90e33

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-crc32c >=1.0,<2.0dev
  run_constrained:
    # extras
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev

test:
  requires:
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - johanneskoester
    - parthea
    - tswast
