schema_version: 1

context:
  name: google-resumable-media
  version: "2.11.0"

package:
  name: google-resumable-media
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: febd83686752799661b4de575f0b993c5c25c349a5362556fc4d7be164056a37

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-crc32c >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - google
        - google.resumable_media
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Utilities for Google Media Downloads and Resumable Uploads
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-resumable-media
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-resumable-media
  documentation: https://googleapis.github.io/google-resumable-media-python/latest/

extra:
  recipe-maintainers:
    - xylar
    - johanneskoester
    - parthea
    - tswast
