travis:
  secure:
    BINSTAR_TOKEN: tBGzVT6VoazNvek19Kl1WfRLSbUUEBbN9RvaoUIWFJ9CUpULjYtocxWicwYCR1lMmIW6bNk5QoaFN0vWDCRWEcIDmEnHsOZcjMyp0Q379EHUtozJCiKCDFVnZh7+hiaB+fxR8U4OxIilTtLvxSsJV98udDf3ncW73Pv+2PWfzSZWzQnS+xQUtnHacY9K6QkWibZyn1jwqj0mnS+iHNfAqNQg5gSqGwL+Iz7VOdyGw0anbRTevjCqpFyNBJWT8EqSpwuchS5jyogx3NaKryusED6/8or1vGyeCYoUWkIMIUmIUFMnO4I588vPzxXKIta6IBt5NkOkwG581sF4QGJE6wRvbOAZDRrDta56TXlrKnkJlU0QNBaZiA+gYoGNoXBXPs/l2jEXvvSTtf30b+/ePSgUpEZ7PcKfQ/nQ2xGB8uFj27l0WzpMf0XxGMoveWj9j0YrgwE/RXWwhQDwe/5zkl5lTB8B9vUwMwcMDIEIqkqzVqgqg/xuaByHEOqtXCbRNHbnl7t4Wdilw8r22J89CdU0fx2l3MDfgPLXYa8v+KbaiKLzZ342tlffVLG71d7YtFsDkLSTYO5XQodN4txxbw0RXyaJycpSHU1P23wyDRozaL7IScTDUiA76vV9gCwA40j0Zp+zyH0wVUu9k+xvKOIVI2hVJl4Ll6hK0p4kD4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
